### ISSUE TITLE
Feature request : Fill object will one color from pallete in object mode.

### ISSUE THREAD

**Issue by harrisyu** [Mahrkeenerh/VertXArtist#2]
I am making flat style character using VertXArist, I normally set 1 color for each parts in object.
I would be nice to have this feature in my workflow.

**Comment by Mahrkeenerh** [comment]
What feature are you requesting?
You can already select the part and assign a color to it.

Can you be more specific?

**Comment by harrisyu** [comment]
> What feature are you requesting? You can already select the part and assign a color to it.
> 
> Can you be more specific?

I mean in Object mode, not in vertex paint mode, I would like to set color for selected object(s). sometimes I have many object to set vertext color, just 1 color for each. 'go vertext paint mode -> select -> set color' is to many step in this case for lots objects.
For example: a head makes of 7 objects, head+2 ears in yellow, nose in pink, hair+ 2 eyes in black.

**Comment by Mahrkeenerh** [comment]
I don't think that will work well in general.
- you don't have the color preview in object mode.
- you could potentially overwrite your other color data (which you also can't see)

A workaround for you may be to merge them all together, color everything, and split in the end.

**Comment by harrisyu** [comment]
> I don't think that will work well in general.
> 
> * you don't have the color preview in object mode.
> * you could potentially overwrite your other color data (which you also can't see)
> 
> A workaround for you may be to merge them all together, color everything, and split in the end.

In viewport shading setting if we set color to attribute it will draw vertex color.
For overwriting exist color data, that's true.
Thanks for your advice anyway. I will see if I can improve my workflow later.
