### ISSUE TITLE
 "Select by color" is not working.

### ISSUE THREAD

**Issue by Kayoua** [Mahrkeenerh/VertXArtist#3]
Hi, and thanks for the great plugin! I sent you a message on Blender Market but thought I try sending a message here too. Unfortunately, the "select by color" is not working for me. I tried this:

Apply several colors to the object
Click the arrow  next to one of the object colors
Expected: all faces with that color are selected
Result: nothing is selected - it actually clears selection entirely, so something is happening. I've tried setting the "tolerance" value to 1.0 also, just in case ... no luck.

However, I noticed it does work for full black or full white faces only.

I tested it with Blender 3.3,  3.4.1 and 3.2 if that helps. Thanks!

**Comment by Mahrkeenerh** [comment]
Yes, I've seen the message, but didn't have time to respond yet. Thanks for the info, I'll look into it, and try to replicate it.

**Comment by paspasion** [comment]
Ok, great, glad you saw the message, thanks!

**Comment by Mahrkeenerh** [comment]
okay, just tested it, and it works fine for me
Blender 3.4.1, VertX Artist 1.3.1

- add new cube
- color faces with set color
- select color

You can try the refresh button, which should force update all colors, in case there are some misalignments or something.

Also, please check the console if you get any errors.
