### ISSUE TITLE
Missing "Adjust Object Colors" palette in version 3.2.2

### ISSUE THREAD

**Issue by Kayoua** [Mahrkeenerh/VertXArtist#6]
I just updated to Blender 4.1 and I also updated to Vertx Artist 3.2.2 and noticed it is missing the Adjust Object Colors palette. Would you be able to fix it? I took a screenshot below you so know what I am talking about. Previously I was using Vertx Artist 1.4.1 with Blender 3.6.1 and it was working fine.

I am also getting an error message when I click the check mark button in the set color palette, I also took a screenshot of that too.

![Screenshot 2024-05-29 220831](https://github.com/Mahrkeenerh/VertXArtist/assets/34899850/604d5a97-31ab-40d0-9304-24caea51ca4e)
 

![Image_](https://github.com/Mahrkeenerh/VertXArtist/assets/34899850/7d28064a-bc24-4e59-a839-819467a2c0b7)

**Comment by Mahrkeenerh** [comment]
Hello, thank you for the issue.

Object color adjusting has been moved to edit mode!

The error you're getting, was it in vertex paint, when you tried to apply a color to a face? I'll have to take a closer look.

**Comment by Kayoua** [comment]
Thanks for looking into that. 
I have another problem I forgot to address about switching face colors in the same mesh. I made a video to better explain it. 
I watched the gifs you posted, but I can't seem to replicate it, unsure if I am doing something wrong or if there's is a glitch, can you look into that, thanks! 

https://github.com/Mahrkeenerh/VertXArtist/assets/34899850/7990acdb-7ba2-4554-a812-dddcabcba153

**Comment by Mahrkeenerh** [comment]
In #7
