### ISSUE TITLE
Adjusting face color on same mesh doesn't work. 

### ISSUE THREAD

**Issue by Kayoua** [Mahrkeenerh/VertXArtist#7]
Hi, I don't know if you saw my comment from the previous issue I reported, just thought if I send a report this way you might be able to see it instead. I am encountering a new problem, I have been having problems adjusting face colors on the same mesh in Edit mode. If I want to make minor tweeks in Edit it doesn't work. I made a video to better explain it. I watched the gifs you posted, but I can't seem to replicate it, unsure if I am doing something wrong or if there's is a glitch, can you look into that? Thanks!

https://github.com/Mahrkeenerh/VertXArtist/assets/34899850/8db5ea2b-2ef6-4938-bd35-6b3b72f97fbc

**Comment by Mahrkeenerh** [comment]
Hello, I did see it, I have it in my todo list, I'm just a little busy right now.

This should definitely not be happening.

Do you have some reproduction steps, so I could arrive at the same problem when trying to find the cause? Thanks

**Comment by Kayoua** [comment]
Certainly! I had my husband help me make this video. I showed him the problems so he could explain what I am struggling with. I can only upload 10mb video so hopefully you can see it well. Let me know if you need more info.

https://github.com/Mahrkeenerh/VertXArtist/assets/34899850/8d61b09a-864e-4944-9e1e-687b29361731

**Comment by Mahrkeenerh** [comment]
What version of the vertex artist are you using?

**Comment by Kayoua** [comment]
The version is 3.2.2

**Comment by Mahrkeenerh** [comment]
Published an updated version, hopefully should work properly now!
