### ISSUE TITLE
Adding colors to custom palette have issues, need help.

### ISSUE THREAD

**Issue by Kayoua** [Mahrkeenerh/VertXArtist#8]
Hello, thanks for solving the other issues, I'm having a new problem where I cannot add colors to the custom palette, I believe the plus icon disappeared. I also looked at the gif you posted on Blender Marketplace and the UI for adding colors seemed to be gone on my end. Please see the attached gif. If you can look into this, that'll be great. I'm using Blender 4.1 and VertX Artist 3.2.3. 

![VXC](https://github.com/user-attachments/assets/bd962257-0c0a-47ed-80b4-50e287a51a72)

**Comment by Mahrkeenerh** [comment]
I believe you need to have the single-column setup. The other ones are more compact, so they are not for editing.

**Comment by Kayoua** [comment]
Ahh, ok thanks! It's working now.
